version: '3'

volumes:
  django_template_local_postgres_data: {}
  django_template_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    image: django_template_local_django
    container_name: django_template_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./envs/local/postgres
    ports:
      - '8000:8000'

  postgres:
    image: postgres:15
    container_name: django_template_local_postgres
    volumes:
      - django_template_local_postgres_data:/var/lib/postgresql/data
      - django_template_local_postgres_data_backups:/backups
    env_file:
      - ./envs/local/postgres
